allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  "msgpackr-extract": true

minimumReleaseAgeExclude:
  - '@playwright/test@1.62.1'
  - playwright-core@1.62.1
  - playwright@1.62.1
  - '@angular/ssr@22.1.4'
